//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDITION
    {
        public string PATIENT_ID { get; set; }
        public string CONDITION_ID { get; set; }
        public string CONDITION1 { get; set; }
        public System.DateTime ONSET_DATE { get; set; }
        public bool ACUTE { get; set; }
        public bool CHRONIC { get; set; }
        public string NOTE { get; set; }
    
        public virtual PATIENT_TBL PATIENT_TBL { get; set; }
    }
}
