CREATE TABLE [dbo].[PATIENT_TBL] (
    [PATIENT_ID]     NCHAR (10)    NOT NULL DEFAULT 0000000001,
    [LAST_NAME]      NVARCHAR (20) NOT NULL DEFAULT Lucey,
    [FIRST_NAME]     NVARCHAR (20) NOT NULL DEFAULT Devon,
    [DATE_Of_BIRTH]  DATE          NULL,
    [ADDRESS_STREET] NVARCHAR (50) NULL,
    [ADDRESS_CITY]   NVARCHAR (20) NULL,
    [ADDRESS_STATE]  NVARCHAR (20) NULL,
    [ADDRESS_ZIP]    NCHAR (10)    NULL,
    [PHONE_HOME]     NCHAR (10)    NULL,
    [PHONE_MOBILE]   NCHAR (10)    NULL,
    [PRIMARY_ID]     NCHAR (10)    NULL,
    CONSTRAINT [PK_PATIENT_TBL] PRIMARY KEY CLUSTERED ([PATIENT_ID] ASC)
);

