//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENT_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PATIENT_TBL()
        {
            this.ALLERGY_TBL = new HashSet<ALLERGY_TBL>();
            this.CONDITIONs = new HashSet<CONDITION>();
            this.IMMUNIZATION_TBL = new HashSet<IMMUNIZATION_TBL>();
            this.MED_PROC_TBL = new HashSet<MED_PROC_TBL>();
            this.MEDICATION_TBL = new HashSet<MEDICATION_TBL>();
            this.TEST_TBL = new HashSet<TEST_TBL>();
        }
    
        public string PATIENT_ID { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public Nullable<System.DateTime> DATE_Of_BIRTH { get; set; }
        public string ADDRESS_STREET { get; set; }
        public string ADDRESS_CITY { get; set; }
        public string ADDRESS_STATE { get; set; }
        public string ADDRESS_ZIP { get; set; }
        public string PHONE_HOME { get; set; }
        public string PHONE_MOBILE { get; set; }
        public string PRIMARY_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALLERGY_TBL> ALLERGY_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONDITION> CONDITIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMMUNIZATION_TBL> IMMUNIZATION_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MED_PROC_TBL> MED_PROC_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICATION_TBL> MEDICATION_TBL { get; set; }
        public virtual PER_DETAILS_TBL PER_DETAILS_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEST_TBL> TEST_TBL { get; set; }
    }
}
