//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pchr42563Entities : DbContext
    {
        public pchr42563Entities()
            : base("name=pchr42563Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALLERGY_TBL> ALLERGY_TBL { get; set; }
        public virtual DbSet<CONDITION> CONDITIONs { get; set; }
        public virtual DbSet<IMMUNIZATION_TBL> IMMUNIZATION_TBL { get; set; }
        public virtual DbSet<MED_PROC_TBL> MED_PROC_TBL { get; set; }
        public virtual DbSet<MEDICATION_TBL> MEDICATION_TBL { get; set; }
        public virtual DbSet<PATIENT_TBL> PATIENT_TBL { get; set; }
        public virtual DbSet<PER_DETAILS_TBL> PER_DETAILS_TBL { get; set; }
        public virtual DbSet<PRIMARY_CARE_TBL> PRIMARY_CARE_TBL { get; set; }
        public virtual DbSet<TEST_TBL> TEST_TBL { get; set; }
    }
}
