//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIMARY_CARE_TBL
    {
        public string PRIMARY_ID { get; set; }
        public string NAME_LAST { get; set; }
        public string NAME_FISRT { get; set; }
        public string TITLE { get; set; }
        public string SPECIALTY { get; set; }
        public string PHONE_OFFICE { get; set; }
        public string PHONE_MOBILE { get; set; }
    }
}
