//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_TBL
    {
        public string PATIENT_ID { get; set; }
        public string TEST_ID { get; set; }
        public string TEST { get; set; }
        public string RESULT { get; set; }
        public System.DateTime DATE { get; set; }
        public string NOTE { get; set; }
    
        public virtual PATIENT_TBL PATIENT_TBL { get; set; }
    }
}
